# Generated by Django 5.0 on 2023-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
